name: flutter_mongodb_realm
description: Unofficial plugin for using services of the serverless platform MongoDB Realm (previously MongoDB Stitch).
version: 2.0.0-nullsafety.0
homepage: https://github.com/kfiross/flutter_mongo_stitch

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_mongo_stitch_platform_interface: ^2.0.0-nullsafety.0
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  flutter_mongo_stitch_web: ^1.0.0-nullsafety.0


  universal_html: ^2.0.8      # instead importing in runtime
  bson: ^1.0.3
  extension: ^0.2.0
  # streams_channe us not nullsafety: using a reimplmented
  # streams_channel2: ^1.0.0
  streams_channel:
    git:
      url: git://github.com/GeghamHayrapetian/streams_channel
      ref: master

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_mongo_stitch
        pluginClass: FlutterMongoStitchPlugin
      ios:
        pluginClass: FlutterMongoStitchPlugin
      web:
        default_package: flutter_mongo_stitch_web
